/**
 * Kafka Topic Enum
 */
export enum WinformTopics {
  WINFORM_LOGGER = 'WINFORM_LOGGER',
  WINFORM_EXCEPTIONS = 'WINFORM_EXCEPTIONS',
  WINFORM_ERROR = 'WINFORM_ERROR',
  WINFORM_OPERATION = 'WINFORM_OPERATION',
}
