export enum RepositoryEnums {
  FACILITY = 'facility',
  ORGANIZATION = 'organization',
  CLASSIFICATION = 'classification',
  FACILITY_STRUCTURE = 'facility_structure',
  FACILITY_HISTORY = 'facility_history',
  CLASSIFICATION_HISTORY = 'classification_history',
  FACILITY_STRUCTURE_HISTORY = 'facility_structure_history',
  ROOM = 'ROOM',
  ROOM_HISTORY = 'ROOM_HISTORY',
  ASSET_STRUCTURE_RELATION = 'ASSET_STRUCTURE_RELATİON',
  FACILITY_STRUCTURE_RELATİON = 'FACILITY_STRUCTURE_RELATİON',
  WINFORM_STRUCTURE_RELATION = 'WINFORM_STRUCTURE_RELATION',
  CONTACT = 'contact',
  WINFORM_STRUCTURE_DATA_OPERATION = 'WINFORM_STRUCTURE_DATA_OPERATION'
}
